### ISSUE TITLE
Comments are global and not stored under the todo

### ISSUE THREAD

**Issue by astromechza** [aurelian-one/au#30]
```
[27-track-email-address-of-user-creating-comments-and-creatingupdating-todos:￪1￬1 bmeier ~/projects/github.com/aurelian-one/au ⟫ au dev export-workspace
alias: Project A
created_at: "2024-02-09T08:39:48Z"
todos:
  01HP6GDNAEA2A3WJ3X7VHE18C8:
    annotations: {}
    created_at: "2024-02-09T08:40:51Z"
    created_by: Ben Meier <ben@meierhost.com>
    description: '&automerge.Text{"something else"}'
    status: open
    title: '&automerge.Text{"Do the thing"}'
    updated_at: "2024-02-09T08:43:46Z"
    updated_by: Ben Meier <ben@meierhost.com>
  comments:
    01HP6GF6VH1NMHF6WMAP789E67:
      content: TmV3IHN0dWZmCg==
      created_at: "2024-02-09T08:41:42Z"
      created_by: Ben Meier <ben@meierhost.com>
      media_type: text/markdown
      updated_at: "2024-02-09T08:44:11Z"
      updated_by: Ben Meier <ben@meierhost.com>
```
